Hopeful updates to Minish Cap cheevos.
MagmarFire/RetroAchievements pull request #102
Opened 2022-12-03 02:16 UTC by wolfman2000

A few things were noticed during my testing offline, so let's put them in the RA Script now. No changes have been published to RA yet.

* Converted all `ScreenId` calls to 16-bit BE format. I've taken enough notes to confirm that the "higher" byte is always the world, and the "lower" is the sub map. This should help maintain map consistency.
* Extracted the line of taking damage to a `TookDamage` function.
* Simplified the Bested Vaati cheevo. We only care about starting the event and ending the event.
* Add Music Protection on Bested Vaati so the cheevo trigger doesn't show on file select.
* Simplified the logic for Bested Big Green Chuchu. Also ensured the trigger icon would show.
* Simplified the logic for Bested Gleerok.
* Simplified the logic for Bested Mazaal.

There's more that can probably be done, but I'm presently on Hot Spot internet, so I can't spend too much time getting things updated to more modern standards.

2023-02-15 23:36 UTC, MagmarFire requested changes
My apologies for not seeing this PR until now!

2023-02-15 23:36 UTC, MagmarFire commented on RA Scripts/Legend of Zelda, The The Minish Cap.rascript
> +function ScreenId() => word_be(0x000BF4)
For memory accessor wrappers, we want to use camelCase. For my scripts, I reserve PascalCase for computables and other functions.

2023-02-15 23:36 UTC, MagmarFire commented on RA Scripts/Legend of Zelda, The The Minish Cap.rascript
> +function TookDamage() => byte(0x00AAEA) < Delta(byte(0x00AAEA))
This should be renamed to `JustTookDamage` to emphasize at a glance that there's no hit target and that it's only ever true in the immediate past.

2023-02-15 23:36 UTC, MagmarFire commented on RA Scripts/Legend of Zelda, The The Minish Cap.rascript
> -
I recommend readding this line to maintain adherence to POSIX (and to reduce the total number of diffs in this PR).

2023-02-15 23:37 UTC, MagmarFire commented on RA Scripts/Legend of Zelda, The The Minish Cap.rascript
> +function ScreenId() => word_be(0x000BF4)
Though I do acknowledge that the original was also in PascalCase. This was an error on my part.

2023-11-19 23:30 UTC, MagmarFire commented
The new changes look good, but there are still unaddressed comments. I won't approve a merge until they're resolved.

2023-11-22 17:34 UTC, wolfman2000 commented
The unaddressed comment should be covered at this point unless I missed another location.

2023-11-26 17:58 UTC, MagmarFire approved these changes

2023-11-26 17:58 UTC, merged